---
kind: pipeline
type: kubernetes
name: Test

platform:
  os: linux
  arch: arm

steps:
  - name: unit test
    image: golang:1.15-stretch
    commands:
      - apt-get update
      - apt-get install -y git build-essential
      - go test -coverprofile cover.out ./...
    resources:
      limits:
        cpu: 1000
        memory: 300MiB

  - name: coverage
    image: golang:1.15-stretch
    commands:
      - go tool cover -func cover.out
    depends_on:
      - unit test

---
kind: pipeline
type: kubernetes
name: Image Staging

depends_on:
- Test

platform:
  os: linux
  arch: arm

steps:
  - name: prepare cache
    image: docker-registry.pikube.dev:31443/drone-genuinetools-img
    settings:
      registry: docker-registry-service.docker-registry:5000
      repo: gobernate
      target: builder
      tags: cache
      cache: true
      cache_image: docker-registry-service.docker-registry:5000/gobernate:cache
      insecure_registry: true
    resources:
      limits:
        cpu: 1000
        memory: 300MiB

  - name: build staging
    image: docker-registry.pikube.dev:31443/drone-genuinetools-img
    settings:
      registry: docker-registry-service.docker-registry:5000
      repo: gobernate
      tags: ${DRONE_BRANCH},unstable
      cache: true
      cache_image: docker-registry-service.docker-registry:5000/gobernate:cache
      insecure_registry: true
    resources:
      limits:
        cpu: 1000
        memory: 300MiB
    depends_on:
      - prepare cache

---
kind: pipeline
type: kubernetes
name: Image Production

trigger:
  event:
  - tag

depends_on:
- Image Staging

platform:
  os: linux
  arch: arm

steps:
  - name: build production
    image: docker-registry.pikube.dev:31443/drone-genuinetools-img
    settings:
      registry: docker-registry-service.docker-registry:5000
      repo: gobernate
      auto_tag: true
      cache: true
      cache_image: docker-registry-service.docker-registry:5000/gobernate:cache
      insecure_registry: true
    resources:
      limits:
        cpu: 1000
        memory: 300MiB

---
kind: signature
hmac: 614066354d8a2161c507172a67f939978f8d02f400e8d71d34bd533d8b65a422

...
