---
kind: pipeline
type: kubernetes
name: Test

platform:
  os: linux
  arch: arm

steps:
  - name: unit test
    image: golang:1.15-stretch
    commands:
      - apt-get update
      - apt-get install -y git build-essential
      - go test -coverprofile cover.out ./...
    resources:
      requests:
        cpu: 1000
        memory: 200MiB

  - name: coverage
    image: golang:1.15-stretch
    commands:
      - go tool cover -func cover.out
    depends_on:
      - unit test

---
kind: pipeline
type: kubernetes
name: Image Staging

depends_on:
- Test

platform:
  os: linux
  arch: arm

steps:
  - name: build staging
    image: docker-registry.pikube.dev:31443/drone-genuinetools-img
    settings:
      registry: docker-registry-service.docker-registry:5000
      repo: gobernate
      tags: ${DRONE_BRANCH},unstable
      insecure_registry: true
    resources:
      requests:
        cpu: 1000
        memory: 300MiB

---
kind: pipeline
type: kubernetes
name: Image Production

trigger:
  event:
  - tag

depends_on:
- Image Staging

platform:
  os: linux
  arch: arm

steps:
  - name: build production
    image: docker-registry.pikube.dev:31443/drone-genuinetools-img
    settings:
      registry: docker-registry-service.docker-registry:5000
      repo: gobernate
      auto_tag: true
      insecure_registry: true
    resources:
      requests:
        cpu: 1000
        memory: 300MiB

---
kind: signature
hmac: 86977609a0e2c16c8c245d10470fc7ebf69baccceb5010fb438aaa26ee50a811

...
