---
kind: pipeline
type: kubernetes
name: Test

platform:
  os: linux
  arch: arm

steps:
  - name: unit-test
    image: golang:1.15-alpine
    commands:
      - |-
        apk add \
            build-base \
            gcc
      - |-
        go test \
          -coverprofile cover.out \
          ./...

  - name: coverage
    image: golang:1.15-alpine
    commands:
      - |-
        go tool cover \
          -func cover.out
    depends_on:
      - unit-test

---
kind: pipeline
type: kubernetes
name: Image

depends_on:
  - Test

platform:
  os: linux
  arch: arm

steps:
  - name: build-test
    image: docker-registry.pikube.dev:31443/drone-genuinetools-img
    settings:
      registry: docker-registry.pikube.dev:31443
      repo: gobernate
      tags:
      - ${DRONE_BRANCH}
      - unstable
      cache: true
      insecure_registry: true
    when:
      event:
        exclude:
          - tag

  - name: build-production
    image: docker-registry.pikube.dev:31443/drone-genuinetools-img
    settings:
      registry: docker-registry.pikube.dev:31443
      repo: gobernate
      auto_tag: true
      cache: true
      insecure_registry: true
    when:
      event:
        - tag

---
kind: signature
hmac: f5398e36124f30a7ce737343add86bc9a29fd1cab54b03c4d05a976de62925ac

...
