---
kind: pipeline
type: kubernetes
name: Test

platform:
  os: linux
  arch: arm

steps:
  - name: unit-test
    image: golang:1.15-alpine
    commands:
      - |-
        apk add \
            build-base \
            gcc
      - |-
        go test \
          -coverprofile cover.out \
          ./...

  - name: coverage
    image: golang:1.15-alpine
    commands:
      - |-
        go tool cover \
          -func cover.out
    depends_on:
      - unit-test

  - name: build-test
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: docker-registry.pikube.dev/gobernate
      tags:
        - unstable
        - $${DRONE_BRANCH}
    when:
      event:
        exclude:
        - tag

  - name: build-production
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: docker-registry.pikube.dev/gobernate
      auto_tag: true
      mirror: docker-mirror.pikube.dev
    when:
      event:
      - tag
---
kind: signature
hmac: 932f6229d27b4cb4e0941721196c7062fd02ca9fcc4a614f92b1c7cfe9a6bafc

...
